fix: [#56147] add aiofiles to pyproject.toml
This fixes the following issue (stacktrace mangled due to incredibly stupid commit linting):
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/dipex/os2mo-data-import-and-export/exporters/os2sync_export/os2sync_export/__main__.py"
, line 19, in <module>
    from os2sync_export import lcdb_os2mo
  File "/opt/dipex/os2mo-data-import-and-export/exporters/os2sync_export/os2sync_export/lcdb_os2mo.p
y", line 22, in <module>
    from exporters.sql_export.lc_for_jobs_db import get_engine  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dipex/os2mo-data-import-and-export/exporters/sql_export/lc_for_jobs_db.py", line 13, in
 <module>
    from .sql_export import SqlExport
  File "/opt/dipex/os2mo-data-import-and-export/exporters/sql_export/sql_export.py", line 20, in <mo
dule>
    from .gql_lora_cache_async import GQLLoraCache
  File "/opt/dipex/os2mo-data-import-and-export/exporters/sql_export/gql_lora_cache_async.py", line
12, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
```